<?php
// 国家码对照表
return [
    ["美国","United States","US","1"],
    ["加拿大","Canada","CA","1"],
    ["香港(中国)","Hong Kong","HK","852"],
    ["台湾(中国)","Taiwan, Province of China","TW","886"],
    ["新加坡","Singapore","SG","65"],
    ["日本","Japan","JP","81"],
    ["韩国","Korea, Republic of","KR","82"],
    ["澳大利亚","Australia","AU","61"],
    ["新西兰","New Zealand","NZ","64"],
    ["阿富汗","Afghanistan","AF","93"],
    ["阿尔巴尼亚","Albania","AL","355"],
    ["阿尔及利亚","Algeria","DZ","213"],
    ["美属萨摩亚(美国)","American Samoa","AS","1684"],
    ["安道尔","Andorra","AD","376"],
    ["安哥拉","Angola","AO","244"],
    ["安圭拉","Anguilla","AI","1264"],
    ["安提瓜和巴布达","Antigua and Barbuda","AG","1268"],
    ["阿根廷","Argentina","AR","54"],
    ["亚美尼亚","Armenia","AM","374"],
    ["阿鲁巴","Aruba","AW","297"],
    ["奥地利","Austria","AT","43"],
    ["阿塞拜疆","Azerbaijan","AZ","994"],
    ["巴哈马","Bahamas","BS","1242"],
    ["巴林","Bahrain","BH","973"],
    ["孟加拉国","Bangladesh","BD","880"],
    ["巴巴多斯","Barbados","BB","1246"],
    ["白俄罗斯","Belarus","BY","375"],
    ["比利时","Belgium","BE","32"],
    ["伯利兹","Belize","BZ","501"],
    ["贝宁","Benin","BJ","229"],
    ["百慕大","Bermuda","BM","1441"],
    ["不丹","Bhutan","BT","975"],
    ["玻利维亚","Bolivia, Plurinational","BO","591"],
    ["波黑","Bosnia and Herzegovina","BA","387"],
    ["博茨瓦纳","Botswana","BW","267"],
    ["巴西","Brazil","BR","55"],
    ["英属维京群岛(英国)","British Virgin Islands","VG","1284"],
    ["文莱","Brunei Darussalam","BN","673"],
    ["保加利亚","Bulgaria","BG","359"],
    ["布基纳法索","Burkina Faso","BF","226"],
    ["布隆迪","Burundi","BI","257"],
    ["柬埔寨","Cambodia","KH","855"],
    ["喀麦隆","Cameroon","CM","237"],
    ["佛得角","Cape Verde","CV","238"],
    ["开曼群岛(英国)","Cayman Islands","KY","1345"],
    ["中非共和国","Central African Republic","CF","236"],
    ["乍得","Chad","TD","235"],
    ["智利","Chile","CL","56"],
    ["哥伦比亚","Colombia","CO","57"],
    ["科摩罗","Comoros","KM","269"],
    ["刚果(金)","Congo, the Democratic Republic of the","CD","243"],
    ["库克群岛(新西兰)","Cook Islands","CK","682"],
    ["哥斯达黎加","Costa Rica","CR","506"],
    ["科特迪瓦","Côte d'Ivoire","CI","225"],
    ["克罗地亚","Croatia","HR","385"],
    ["古巴","Cuba","CU","53"],
    ["塞浦路斯","Cyprus","CY","357"],
    ["捷克","Czech Republic","CZ","420"],
    ["丹麦","Denmark","DK","45"],
    ["吉布提","Djibouti","DJ","253"],
    ["多米尼克","Dominica","DM","1767"],
    ["多米尼加共和国","Dominican Republic","DO","1809"],
    ["厄瓜多尔","Ecuador","EC","593"],
    ["埃及","Egypt","EG","20"],
    ["萨尔瓦多","El Salvador","SV","503"],
    ["赤道几内亚","Equatorial Guinea","GQ","240"],
    ["厄立特里亚","Eritrea","ER","291"],
    ["爱沙尼亚","Estonia","EE","372"],
    ["埃塞俄比亚","Ethiopia","ET","251"],
    ["法罗群岛(丹麦)","Faroe Islands","FO","298"],
    ["斐济","Fiji","FJ","679"],
    ["芬兰","Finland","FI","358"],
    ["法国","France","FR","33"],
    ["法属圭亚那(法国)","French Guiana","GF","594"],
    ["法属玻利尼西亚","French Polynesia","PF","689"],
    ["加蓬","Gabon","GA","241"],
    ["冈比亚","Gambia","GM","220"],
    ["格鲁吉亚","Georgia","GE","995"],
    ["德国","Germany","DE","49"],
    ["加纳","Ghana","GH","233"],
    ["直布罗陀(英国)","Gibraltar","GI","350"],
    ["希腊","Greece","GR","30"],
    ["格陵兰","Greenland","GL","299"],
    ["格林纳达","Grenada","GD","1473"],
    ["瓜德罗普","Guadeloupe","GP","590"],
    ["关岛(美国)","Guam","GU","1671"],
    ["危地马拉","Guatemala","GT","502"],
    ["几内亚","Guinea","GN","224"],
    ["几内亚比绍","Guinea-Bissau","GW","245"],
    ["圭亚那","Guyana","GY","592"],
    ["海地","Haiti","HT","509"],
    ["洪都拉斯","Honduras","HN","504"],
    ["匈牙利","Hungary","HU","36"],
    ["冰岛","Iceland","IS","354"],
    ["印度","India","IN","91"],
    ["印度尼西亚","Indonesia","ID","62"],
    ["伊朗","Iran, Islamic Republic of","IR","98"],
    ["伊拉克","Iraq","IQ","964"],
    ["爱尔兰共和国","Ireland","IE","353"],
    ["以色列","Israel","IL","972"],
    ["意大利","Italy","IT","39"],
    ["牙买加","Jamaica","JM","1876"],
    ["约旦","Jordan","JO","962"],
    ["哈萨克斯坦","Kazakhstan","KZ","73"],
    ["肯尼亚","Kenya","KE","254"],
    ["基里巴斯","Kiribati","KI","686"],
    ["北朝鲜","Korea, Democratic People's Republic of","KP","850"],
    ["科威特","Kuwait","KW","965"],
    ["吉尔吉斯斯坦","Kyrgyzstan","KG","996"],
    ["老挝","Lao People's Democratic Republic","LA","856"],
    ["拉脱维亚","Latvia","LV","371"],
    ["黎巴嫩","Lebanon","LB","961"],
    ["莱索托","Lesotho","LS","266"],
    ["利比里亚","Liberia","LR","231"],
    ["利比亚","Libya","LY","218"],
    ["列支敦士登","Liechtenstein","LI","423"],
    ["立陶宛","Lithuania","LT","370"],
    ["卢森堡","Luxembourg","LU","352"],
    ["澳门(中国)","Macao","MO","853"],
    ["马其顿","Macedonia, the former Yugoslav Republic of","MK","389"],
    ["马达加斯加","Madagascar","MG","261"],
    ["马拉维","Malawi","MW","265"],
    ["马来西亚","Malaysia","MY","60"],
    ["马尔代夫","Maldives","MV","960"],
    ["马里共和国","Mali","ML","223"],
    ["马耳他","Malta","MT","356"],
    ["马绍尔群岛","Marshall islands","MH","692"],
    ["马提尼克(法国)","Martinique","MQ","596"],
    ["毛里塔尼亚","Mauritania","MR","222"],
    ["毛里求斯","Mauritius","MU","230"],
    ["马约特","Mayotte","YT","262"],
    ["墨西哥","Mexico","MX","52"],
    ["密克罗尼西亚联邦","Micronesia, Federated States of","FM","691"],
    ["摩尔多瓦","Moldova, Republic of","MD","373"],
    ["摩纳哥","Monaco","MC","377"],
    ["蒙古国","Mongolia","MN","976"],
    ["黑山共和国","Montenegro","ME","382"],
    ["蒙塞拉特岛(英国)","Montserrat","MS","1664"],
    ["摩洛哥","Morocco","MA","212"],
    ["莫桑比克","Mozambique","MZ","258"],
    ["缅甸","Myanmar","MM","95"],
    ["纳米比亚","Namibia","NA","264"],
    ["瑙鲁","Nauru","NR","674"],
    ["尼泊尔","Nepal","NP","977"],
    ["荷属安的列斯","Netheriands Antilles","AN","599"],
    ["荷兰","Netherlands","NL","31"],
    ["新喀里多尼亚(法国)","New Caledonia","NC","687"],
    ["尼加拉瓜","Nicaragua","NI","505"],
    ["尼日尔","Niger","NE","227"],
    ["尼日利亚","Nigeria","NG","234"],
    ["纽埃","Niue","NU","683"],
    ["北马里亚纳群岛(美国)","Northern Mariana Islands","MP","1670"],
    ["挪威","Norway","NO","47"],
    ["阿曼","Oman","OM","968"],
    ["巴基斯坦","Pakistan","PK","92"],
    ["帕劳","Palau","PW","680"],
    ["巴勒斯坦","Palestine, State of","PS","970"],
    ["巴拿马","Panama","PA","507"],
    ["巴布亚新几内亚","Papua New Guinea","PG","675"],
    ["巴拉圭","Paraguay","PY","595"],
    ["中国","China","CN","86"],
    ["秘鲁","Peru","PE","51"],
    ["菲律宾","Philippines","PH","63"],
    ["波兰","Poland","PL","48"],
    ["葡萄牙","Portugal","PT","351"],
    ["波多黎各(美国)","Puerto Rico","PR","1809"],
    ["卡塔尔","Qatar","QA","974"],
    ["刚果共和国","Republic of the Congo","CG","242"],
    ["津巴布韦","Republic of Zimbabwe","ZW","263"],
    ["留尼汪(法国)","Reunion Island","RE","262"],
    ["罗马尼亚","Romania","RO","40"],
    ["俄罗斯","Russian Federation","RU","7"],
    ["卢旺达","Rwanda","RW","250"],
    ["圣赫勒拿","Saint Helena","SH","290"],
    ["圣基茨和尼维斯","Saint Kitts and Nevis","KN","1869"],
    ["圣卢西亚","Saint Lucia","LC","1758"],
    ["圣皮埃尔和密克隆岛(法国)","Saint Pierre and Miquelon","PM","508"],
    ["圣文森特和格林纳丁斯","Saint Vincent and the Grenadines","VC","1784"],
    ["萨摩亚","Samoa","WS","685"],
    ["圣马力诺","San Marino","SM","223"],
    ["圣多美和普林西比","Sao Tome and Principe","ST","239"],
    ["沙特阿拉伯","Saudi Arabia","SA","966"],
    ["塞内加尔","Senegal","SN","221"],
    ["塞尔维亚共和国","Serbia","RS","381"],
    ["塞舌尔","Seychelles","SC","248"],
    ["塞拉利昂","Sierra Leone","SL","232"],
    ["斯洛伐克","Slovakia","SK","421"],
    ["斯洛文尼亚","Slovenia","SI","386"],
    ["所罗门群岛","Solomon Islands","SB","677"],
    ["索马里","Somalia","SO","252"],
    ["南非","South Africa","ZA","27"],
    ["南苏丹","South Sudan","SS","211"],
    ["西班牙","Spain","ES","34"],
    ["斯里兰卡","Sri Lanka","LK","94"],
    ["苏丹","Sudan","SD","249"],
    ["苏里南","Suriname","SR","597"],
    ["斯威士兰","Swaziland","SZ","268"],
    ["瑞典","Sweden","SE","46"],
    ["瑞士","Switzerland","CH","41"],
    ["叙利亚","Syrian Arab Republic","SY","963"],
    ["塔吉克斯坦","Tajikistan","TJ","992"],
    ["坦桑尼亚","Tanzania, United Republic of","TZ","255"],
    ["泰国","Thailand","TH","66"],
    ["东帝汶","Timor-Leste","TL","670"],
    ["多哥","Togo","TG","228"],
    ["托克劳","Tokelau","TK","690"],
    ["汤加","Tonga","TO","676"],
    ["特立尼达和多巴哥","Trinidad and Tobago","TT","1868"],
    ["突尼斯","Tunisia","TN","216"],
    ["土耳其","Turkey","TR","90"],
    ["土库曼斯坦","Turkmenistan","TM","993"],
    ["特克斯和凯科斯群岛(英国)","Turks and Caicos Islands","TC","1649"],
    ["图瓦卢","Tuvalu","TV","688"],
    ["乌干达","Uganda","UG","256"],
    ["乌克兰","Ukraine","UA","380"],
    ["阿拉伯联合酋长国","United Arab Emirates","AE","971"],
    ["英国","United Kingdom","GB","44"],
    ["乌拉圭","Uruguay","UY","598"],
    ["乌兹别克斯坦","Uzbekistan","UZ","998"],
    ["瓦努阿图","Vanuatu","VU","678"],
    ["委内瑞拉","Venezuela, Bolivarian Republic of","VE","58"],
    ["越南","Vietnam","VN","84"],
    ["瓦利斯和富图纳群岛(法国)","Wallis and Futuna","WF","681"],
    ["也门","Yemen","YE","967"],
    ["赞比亚","Zambia","ZM","260"]
];
